import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {cellsFor,sizedMessages,MIXED_BYTES,candidateEnv,heavyBatchStats,matchedSchedule,vmRssBytes} from './matrix.mjs';
import {identity,verifyRequests,requireClean,small,verifyTelemetry} from './contracts.mjs';
import {rng,shuffled} from './harness.mjs';
for(const [mode,n] of Object.entries({spacing:4,protection:4,tls:4,prepare:8,encoding:6,upload:10,backlog:8,threshold:60,mixed:3,sustained:1,'matched-sustained':1})) assert.equal(cellsFor(mode).length,n);
assert(cellsFor('spacing').every(c=>c.n===8&&c.probes===100&&!c.repeated));
assert(cellsFor('protection').every(c=>c.repeated));
assert.deepEqual(MIXED_BYTES,[2097152,307200,2097152,716800,1363149]);
assert(cellsFor('mixed').every(c=>c.n===5));
const env=candidateEnv({candidateSpacing:'20',candidateThreshold:'131072'});
assert.equal(env.TRAFFIC_PACING_SPACING_MS,'20');assert.equal(env.TRAFFIC_PACING_THRESHOLD,'131072');
assert.equal({...env,...cellsFor('upload')[0].env}.TRAFFIC_PACER,'off');
assert.throws(()=>candidateEnv({candidateSpacing:'bad'}));
const tel={dropped:0,lagMs:[0],admissions:[{actualBytes:300000}]};
verifyTelemetry(tel,[sizedMessages(300000)]);
assert.throws(()=>verifyTelemetry({...tel,lagMs:[]},[sizedMessages(300000)]));
assert.throws(()=>verifyTelemetry({...tel,admissions:[]},[sizedMessages(300000)]));
verifyTelemetry({...tel,admissions:[]},[sizedMessages(300000)],{TRAFFIC_PACER:'off'});
verifyTelemetry({...tel,admissions:[]},[small]);
assert(['prepare','encoding','upload','backlog','threshold','mixed'].every(m=>cellsFor(m).every(c=>c.probes===100)));
const grid=[...new Set([...[64,128,192,256,384,512,768,1024,1741].map(k=>k*1024),...[128,256,512].flatMap(t=>[t*1024-1,t*1024+1])])];
assert.equal(grid.length,15);
for(const policy of ['OFF','128','256','512']) {
  const cells=cellsFor('threshold').filter(c=>c.name.startsWith(policy+'/'));
  assert.deepEqual([...new Set(cells.map(c=>c.bytes))].sort((a,b)=>a-b),[...new Set(grid)].sort((a,b)=>a-b),policy+' identical grid');
  assert(cells.every(c=>c.probes===100&&c.n===8));
  assert(cells.every(c=>policy==='OFF'?c.env.TRAFFIC_PACER==='off'&&c.env.TRAFFIC_PACING_THRESHOLD===undefined:c.env.TRAFFIC_PACING_THRESHOLD===policy*1024+''));
}
assert.equal(cellsFor('threshold').length,4*15);
for(const t of [128,256,512]) assert(grid.includes(t*1024),'exact-at in grid via base sizes');
for(const t of [128,256,512]) assert(cellsFor('threshold').some(c=>c.bytes===t*1024),'missing exact-at '+t);
assert(heavyBatchStats([]).heavyBatchWallMs===null);
assert(heavyBatchStats([{kind:'heavy',error:'x',endOffsetMs:5}]).heavyBatchWallMs===null);
const hb=heavyBatchStats([{kind:'heavy',endOffsetMs:120.456},{kind:'heavy',endOffsetMs:99.1},{kind:'victim',endOffsetMs:500}]);
assert.equal(hb.heavyBatchWallMs,120.46);assert.equal(hb.heavyFirstByteMs.length,2);
for(const c of cellsFor('threshold')) assert.equal(identity(sizedMessages(c.bytes)).bytes,c.bytes);
const id=identity(small),stats={requests:2,aborted:0,bytesReceived:2*id.bytes,identities:{[id.bytes+':'+id.hash]:2}};
assert(verifyRequests(stats,[small,small]).verified);
assert.throws(()=>verifyRequests({...stats,requests:1},[small,small]));
assert.throws(()=>verifyRequests({...stats,identities:{}},[small,small]));
assert.throws(()=>verifyRequests({...stats,bytesReceived:0},[small,small]));
assert.throws(()=>requireClean([{verified:true,errors:1}]));
assert.throws(()=>requireClean([]));
assert.throws(()=>requireClean([{verified:false}]));
requireClean([{verified:true,errors:0}]);
const random=rng(42);for(let i=0;i<5;i++) assert.deepEqual(shuffled([0,10,15,20],random).sort((a,b)=>a-b),[0,10,15,20]);
// Wiring guards without launching a gateway or generating benchmark load.
const driver=readFileSync(new URL('./matrix.mjs',import.meta.url),'utf8');
assert(driver.includes('Promise.all([...workers,victim()])'),'sustained victim must be invoked');
assert(!/assert[^;]*tunnelsActive/.test(driver),'settled tunnels remain observations');
for(const mode of ['spacing','protection','tls','prepare','encoding','upload','backlog','threshold','mixed']) assert(cellsFor(mode).every(c=>c.probes===100),mode+' requires 100 probes');
assert(driver.includes("if(!cell.sustained&&!cell.matched) assert.equal(row.samples.filter(s=>s.kind==='victim').length,100"),'enforce burst probe count');
assert(driver.includes('backlogBreaches.length,0'),'matched backlog breach must fail explicitly');
assert(driver.includes('cross-runtime expected payload multiset mismatch'),'cross-runtime multiset guard');
assert(driver.includes("vmRssBytes(fs.readFileSync('/proc/'+g.child.pid+'/status'"),'settle reads /proc RSS directly');
assert(driver.includes('gatewayStarttime'),'gateway pid/starttime recorded');
assert(driver.includes('row.windowWallMs=row.wallMs')&&driver.includes('Object.assign(row,heavyBatchStats(row.samples))'),'separate heavy and probe-window timing');
// matched-sustained: deterministic identical-across-runtimes schedule + RSS parser.
assert.equal(cellsFor('matched-sustained').length,1);
assert(cellsFor('matched-sustained')[0].matched===true);
const a=matchedSchedule(),b=matchedSchedule();
assert.deepEqual(a,b,'schedule must be deterministic');
assert.equal(a.windowMs,75000);assert.ok(a.cadenceMs>0);assert.ok(Number.isInteger(a.maxOutstanding)&&a.maxOutstanding>0);
assert.equal(a.items.length,1876);
const offsets=a.items.map(x=>x.offsetMs);
assert(offsets.every((v,i)=>i===0||v>offsets[i-1]),'offsets monotonic');
assert(Math.max(...offsets)<=a.windowMs);
assert(a.items.every(x=>x.checkpoint===Math.min(3,Math.floor(x.offsetMs/18750))),'checkpoint derived from scheduled offset');
assert(a.items.every(x=>x.role==='victim'?!x.proxy:true),'victims never proxied');
assert(a.items.every(x=>['victim','parent','child'].includes(x.role)));
assert.equal(a.items.filter(x=>x.role==='victim').length,a.items.filter((_,i)=>i%9===0).length);
assert.equal(vmRssBytes('VmRSS:\t 4096 kB'),4194304);
assert.equal(vmRssBytes('VmRSS:  1 kB'),1024);
assert.equal(vmRssBytes(''),null);assert.equal(vmRssBytes('VmRSS: x kB'),null);assert.equal(vmRssBytes('Other: 5 kB\nVmRSS: 7 kB'),7168);
console.log('matrix correctness checks passed; no load benchmark run');
