import assert from 'node:assert/strict';
import {cellsFor,sizedMessages} from './matrix.mjs';
import {identity,verifyRequests,requireClean,small} from './contracts.mjs';
import {rng,shuffled} from './harness.mjs';
for(const [mode,n] of Object.entries({spacing:4,protection:4,tls:4,prepare:8,encoding:6,upload:10,backlog:8,threshold:9,mixed:3,sustained:1})) assert.equal(cellsFor(mode).length,n);
assert(cellsFor('spacing').every(c=>c.n===8&&c.probes===100&&!c.repeated));
assert(cellsFor('protection').every(c=>c.repeated));
for(const c of cellsFor('threshold')) assert.equal(identity(sizedMessages(c.bytes)).bytes,c.bytes);
const id=identity(small),stats={requests:2,aborted:0,bytesReceived:2*id.bytes,identities:{[id.bytes+':'+id.hash]:2}};
assert(verifyRequests(stats,[small,small]).verified);
assert.throws(()=>verifyRequests({...stats,requests:1},[small,small]));
assert.throws(()=>verifyRequests({...stats,identities:{}},[small,small]));
assert.throws(()=>verifyRequests({...stats,bytesReceived:0},[small,small]));
assert.throws(()=>requireClean([{verified:true,errors:1}]));
assert.throws(()=>requireClean([]));
assert.throws(()=>requireClean([{verified:false}]));
requireClean([{verified:true,errors:0}]);
const random=rng(42);for(let i=0;i<5;i++) assert.deepEqual(shuffled([0,10,15,20],random).sort((a,b)=>a-b),[0,10,15,20]);
console.log('matrix correctness checks passed; no load benchmark run');
